apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: demo-test-chatbot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-test-chatbot 
  name: demo-test-chatbot
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demo-test-chatbot 
    weight: 100 
  wildcardPolicy: None
